[package]
name = "paging"
version = "0.1.0"
edition.workspace = true
description = "Generic page table structures for Rust OS projects"

[dependencies]
bitflags.workspace = true
zerocopy.workspace = true
verus_stub.workspace = true
core_proofs = { workspace = true, optional = true }
external_specs = { workspace = true, optional = true }
vstd = { workspace = true, optional = true }

[features]
default = []
verus = ["core_proofs", "external_specs", "vstd", "verus_stub/disable"]

[package.metadata.verus]
verify = true

[lints]
workspace = true
